load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "vector",
    srcs = [],
    hdrs = ["vector.h"],
    include_prefix = ".",
    visibility = ["//visibility:public"],
)

cc_library(
    name = "map",
    srcs = [],
    hdrs = ["map.h"],
    include_prefix = ".",
    visibility = ["//visibility:public"],
    deps = [":list"],
)

cc_library(
    name = "list",
    srcs = [],
    hdrs = ["list.h"],
    include_prefix = ".",
    visibility = ["//visibility:public"],
)

cc_library(
    name = "stack",
    srcs = [],
    hdrs = ["stack.h"],
    include_prefix = ".",
    visibility = ["//visibility:public"],
    deps = [":list"],
)

cc_library(
    name = "pointer",
    srcs = [],
    hdrs = ["unique_ptr.h"],
    include_prefix = ".",
    visibility = ["//visibility:public"],
)

cc_library(
    name = "heap",
    srcs = [],
    hdrs = ["heap.h"],
    include_prefix = ".",
    visibility = ["//visibility:public"],
)
