load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "vector",
    srcs = [],
    hdrs = ["vector.h"],
    include_prefix = ".",
    visibility = ["//visibility:public"],
)

cc_library(
    name = "map",
    srcs = [],
    hdrs = ["map.h"],
    include_prefix = ".",
    visibility = ["//visibility:public"],
)
